###############################################################################
#                                                                             #
#                              Haros analysys                                 #
#                                                                             #
###############################################################################

ARG BONSAI_HASH
ARG HAROS_HASH
ARG PACKAGE_ID

FROM davla/thesis:${PACKAGE_ID} AS package

FROM davla/thesis:haros-${HAROS_HASH}-bonsai-${BONSAI_HASH}

ARG PACKAGE
ARG PACKAGE_NAME
ARG ROS_DISTRO

# Copying the result of package build in the haros image
COPY --from=package --chown=ros:ros /home/ros/catkin_ws /home/ros/catkin_ws
COPY --from=package --chown=root:root /usr/include /usr/include
COPY --from=package --chown=root:root /opt/ros /opt/ros

# Setting Haros up haros
WORKDIR /home/ros/haros
RUN bash -c "source /opt/ros/$ROS_DISTRO/setup.bash \
    && source /home/ros/catkin_ws/devel/setup.bash \
    && python -m haros init"
COPY --chown=ros:ros ./configs.yaml /home/ros/.haros/configs.yaml
COPY --chown=ros:ros ./project.yaml /home/ros/.haros/index.yaml

# Dynamic generation of package configuration: all launch files are added
RUN echo "\n\
packages:\n\
  - $PACKAGE\n\
\n\
configurations:\n\
  massive-analysis:" >> /home/ros/.haros/index.yaml
RUN bash -c "source /opt/ros/$ROS_DISTRO/setup.bash \
    && source /home/ros/catkin_ws/devel/setup.bash \
    && rospack find $PACKAGE_NAME | xargs -i find '{}' -name '*.launch' \
        -printf \"    - $PACKAGE/%P\n\" >> ./launch_files.txt \
    && { test -s ./launch_files.txt \
        && cat ./launch_files.txt >> /home/ros/.haros/index.yaml \
        || echo '    []' >> /home/ros/.haros/index.yaml; } \
    && rm ./launch_files.txt"

# Running the analysis
COPY --chown=ros:ros ./analysis.sh ./analysis.sh
COPY --chown=ros:ros ./fault-injection.sh ./fault-injection.sh
CMD ["bash", "fault-injection.sh"]
